#!/usr/bin/zsh

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="$(file%.*)"
shebang=$(sed -n 1p "$file")

cd "$dir" || exit

textype() { \
        command="pdflatex"
        (sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"
        $command --output-directory="$dir" "$base" &&
        grep -i addbibresource "$file" >/dev/null &&
        biber --input-directory "$dir" "$base" &&
        $command --output-directory="$dir" "$base"
        }

shebangtest() {
        case "$shebang" in
            \#\!*) "$file" ;;
            *) sent "$file" 2>/dev/nill & ;;
        esac
}

case "$file" in
        *\.tex) textype "$file" ;;
        *config.h) make && sudo make install
        *\.c) cc "$file" -o "$base" && "$base" ;;
        *\.py) python "$file" ;;
        *) shebangtest ;;
esac
