#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a pavucontrol desktop='^9' follow=on
bspc rule -a firefox desktop='^1' follow=on

# AutoStart
sxhkd &
redshift &
xautolock -time 60 -locker 'systemctl suspend' &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
firefox &
pulseaudio --start &
pavucontrol &
